geomet_climate/mapfile.py, geomet_climate/resources/mapserv/templates/TEMPLATE_AHCCD.STATIONS.json, geomet_climate/resources/mapserv/templates/TEMPLATE_CLIMATE.STATIONS.json, geomet_climate/resources/mapserv/templates/TEMPLATE_HYDROMETRIC.STATIONS.json, geomet_climate/resources/mapserv/templates/TEMPLATE_RASTER.json, geomet_climate/tileindex.py
This fixes the GetFeatureInfo request for the stations layers in Json.
I had to create new Json templates for the 3 stations layers.
=> fixed GetFeatureInfo in JSON

.travis.yml, geomet_climate/mapfile.py, geomet_climate/tileindex.py, geomet_climate/vrt.py, geomet_climate/wsgi.py
- various Python 2 / 3 compatibility fixes
- uses `io.open`
- add GDAL deps to travis setup
- fix flake8 errors
- removes OGR spatial index creation (done by default for GPKG)
=> fix travis build

geomet_climate/mapfile.py, geomet_climate/tileindex.py, geomet_climate/vrt.py
Added CLoader for Yaml for performances
=> add CLoader for yaml

geomet_climate/tileindex.py
Per subject, this PR tries to optimize GeoPackage files and uses GDAL's Python API to close the file safely.
=> vacuum the tileindex and close the file safely

geomet-climate.yml
added missing layer : DCS.PR.RCP26.ENS.ABS_PCTL95 as reported by a user
=> added missing layer : DCS.PR.RCP26.ENS.ABS_PCTL95

geomet-climate.yml
updated geomet-climate yaml to add the updated cangrid time step
=> update cangrd time step

geomet-climate.yml
First merge to add SPEI data to geomet-climate
=> add spei layers

geomet_climate/resources/mapserv/class/spei.json
add style for spei based on CCCS requirements
=> add spei style

geomet-climate.yml, geomet_climate/resources/mapserv/class/cdd.json, geomet_climate/resources/mapserv/class/gsc_gsw_gso.json, geomet_climate/resources/mapserv/class/hdd.json, geomet_climate/resources/mapserv/class/prep1.json, geomet_climate/resources/mapserv/class/spei.json, geomet_climate/resources/mapserv/class/tx30_tn20.json
First commit for new indices layers. Needs to be merged so I can validate them on nightly and show examples to our CCCS colleagues.
=> added indices layers

debian/postinst, geomet-climate.yml, geomet_climate/__init__.py, geomet_climate/legend.py, geomet_climate/mapfile.py, geomet_climate/resources/mapserv/class/precip_trend.json, geomet_climate/resources/mapserv/class/sea-ice-thickness_absolute.json, geomet_climate/resources/mapserv/class/spei.json, geomet_climate/resources/mapserv/class/temp_anomalies.json, geomet_climate/wsgi.py, requirements.txt
In this merge requests are the necessary changes to create nice legends using matplotlib and numoy.
Those legends are only generated at built time. I had to add 2 dependencies : matplotlib and numpy, but these are required at built time, but not at run time.
before merging we need to validate the different legends with CCCS
cc @tomkralidis for comments on code
=> commit for adding nicer legends

README.md, geomet_climate/legend.py, geomet_climate/resources/mapserv/class/wind_anomaly.json, requirements.txt
add fix for old matplotlib on ubuntu 14.04
=> add fix for old matplotlib on ubuntu 14.04

geomet_climate/wsgi.py
moved mapfile up to avoid errors if no legends are pre-generated
=> moved mapfile up to avoid errors

.travis.yml, geomet_climate/resources/mapserv/templates/TEMPLATE_RASTER.json, tests/geomet-climate-test.yml
added layer name in the json answer at the FeatureCollection level.
=> added layer name in the json answer

.travis.yml, geomet_climate/mapfile.py, geomet_climate/tileindex.py, geomet_climate/vrt.py, geomet_climate/wsgi.py, requirements.txt, tests/run_tests.py
=> update for bionic

geomet-climate.yml, geomet_climate/mapfile.py, geomet_climate/tileindex.py, tests/run_tests.py
updated timstamp to work with gdal 3 and ampserver SQL request
required format is `YYYY-MM-DDThh:mm:ss`
=> updated timestamp to work with gdal 3 and MapServer SQL request

geomet-climate.env, geomet_climate/env.py, geomet_climate/mapfile.py
This PR adds OWS logging if specified via environment variables.
cc @flaframboise
=> add OWS logging

geomet_climate/resources/mapserv/epsg
I fixed the CANGRD layers projection problems in nightly. I delete the `+k` key in all projections that was causing problems in proj4 strings.
=> fixed CANGRD proj problems

geomet-climate.yml, tests/geomet-climate-test.yml
Following a request, I changed the main contact email address from `info.cccs-ccsc@canada.ca` to `ccsc-cccs@ec.gc.ca`
=> Update main contact email address

geomet_climate/mapfile.py
As per https://github.com/MapServer/MapServer/issues/6461#issuecomment-1022173562
=> add CONNECTIONOPTION for ES layers

docker/docker-compose.override.yml, docker/docker-compose.yml
=> use network_mode host for internal connectivity

geomet-climate.yml
update layer tree in GetCap
see issue 636
cc @alexandreleroux
=> update layer tree in GetCap

geomet-climate.yml, geomet_climate/legend.py, geomet_climate/resources/mapserv/class/sea-ice-thickness_absolute_0-2.json
BUGFIX: fix for sea ice thickness style. Also added a second SIT style for lower values because the layer style was not precise enough for smaller SIT values.
=> BUGFIX: fix for SIT styles

Dockerfile, docker/README.md, docker/docker-compose.override.yml, docker/docker-compose.yml
I updated all docker configuration for dev-21, this was causing the nightly to send request to the old dev server.
cc @kngai
=> update docker for dev-21

debian/changelog
This PR updates the `debian/changelog` of the existing `1.10.0` version
=> Update release version 1.10.0

geomet-climate.yml, geomet_climate/mapfile.py
Issue 574 - new CanDCSU6 data
new version of the previous DCS model
=> Issue 574 - new CanDCSU6 data

geomet-climate.yml
update CanDCSU6 layers
* Added missing layers
* Updated band number for some seasonal and monthly layers
=> update CanDCSU6 layers

Dockerfile, deploy/nightly-docker/deploy-nightly-docker.sh, docker/README.md, docker/docker-compose.override.yml, docker/docker-compose.yml
This PR updates the configuration of the nightly Docker build to point to geomet-dev-22
=> Nightly docker build updates for geomet-dev-22

Dockerfile, deploy/nightly-docker/deploy-nightly-docker.sh, docker/README.md, docker/docker-compose.override.yml, docker/docker-compose.yml
- ubuntu:jammy
- Testing with wmo-staging PPA
- Check to ensure required ENVs are set
- Add SSL ceritficate volume mounts for dev-31
=> Docker changes for dev-31:
